const $ = id => document.getElementById(id);
const sourceMode=$('sourceMode'), sourceHint=$('sourceHint'), navigationFields=$('navigationFields'), batchFields=$('batchFields'), profileFields=$('profileFields');
const serverSelect=$('server'), channelSelect=$('channel'), batchServer=$('batchServer'), batchChannels=$('batchChannels');
const profileName=$('profileName'), profileSelect=$('profileSelect'), saveProfileButton=$('saveProfileButton'), deleteProfileButton=$('deleteProfileButton'), refreshProfilesButton=$('refreshProfilesButton');
const range=$('range'), customRange=$('customRange'), startInput=$('start'), endInput=$('end'), runtimeFields=$('runtimeFields'), runtimeLimit=$('runtimeLimit'), runtimeCustomMinutes=$('runtimeCustomMinutes'), loadOlder=$('loadOlder');
const exportButton=$('exportButton'), monitorButton=$('monitorButton'), topologyButton=$('topologyButton'), refreshButton=$('refreshButton'), healthButton=$('healthButton'), status=$('status');
let activeTabId=null, navigation={workspaces:[],sourcesByWorkspace:{}}, currentConversation=null, profiles=[], activeAdapter={platform:'unknown',labels:{}};
const setStatus=message=>{status.textContent=message;};
function updateTimeControls(){customRange.hidden=range.value!=='custom';runtimeFields.hidden=range.value==='visible'||!loadOlder.checked;runtimeCustomMinutes.hidden=runtimeLimit.value!=='custom';}
range.addEventListener('change',updateTimeControls);loadOlder.addEventListener('change',updateTimeControls);runtimeLimit.addEventListener('change',updateTimeControls);

function getBounds(){const now=new Date();let start=null,end=null;const durations={'24h':86400000,'48h':172800000,'7d':604800000,'30d':2592000000,'90d':7776000000,'1y':31557600000,'2y':63115200000,'3y':94672800000};if(durations[range.value])start=new Date(now-durations[range.value]);if(range.value==='custom'){if(!startInput.value||!endInput.value)throw new Error('Choose both a start and end time.');start=new Date(startInput.value);end=new Date(endInput.value);if(!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())||start>=end)throw new Error('The custom time range is invalid.');}return{startIso:start?start.toISOString():null,endIso:end?end.toISOString():null};}
function getMaxRuntimeMs(){if(runtimeLimit.value!=='custom')return Number(runtimeLimit.value);const minutes=Number(runtimeCustomMinutes.value);if(!Number.isFinite(minutes)||minutes<5||minutes>1440)throw new Error('Custom runtime must be between 5 and 1,440 minutes.');return Math.round(minutes*60000);}
function getOptions(){const maxRuntimeMs=getMaxRuntimeMs();return{...getBounds(),format:'json',loadOlder:loadOlder.checked,maxRuntimeMs,intent:'archival',runtimePolicy:{historicalRuntimeMs:maxRuntimeMs}};}
async function getActivePlatformTab(){const[tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab?.id)throw new Error('Open a supported source in the active tab first.');return tab;}
async function send(message,attempts=80){let lastError;for(let i=0;i<attempts;i++){try{const response=await chrome.tabs.sendMessage(activeTabId,message);if(response)return response;}catch(error){lastError=error;}await new Promise(r=>setTimeout(r,300));}throw new Error(lastError?.message||'No installed adapter recognizes the active source.');}
function fill(select,items,selected=null){select.innerHTML='';for(const item of items){const o=document.createElement('option');o.value=item.id;o.textContent=item.name;o.dataset.url=item.url||'';if(item.id===selected)o.selected=true;select.appendChild(o);}select.disabled=!items.length;}
function workspaceById(id){return navigation.workspaces.find(x=>x.id===id)||null;}
function sourceById(workspaceId,id){return(navigation.sourcesByWorkspace?.[workspaceId]||[]).find(x=>x.id===id)||null;}
function targetFrom(workspaceId,sourceId){const w=workspaceById(workspaceId),s=sourceById(workspaceId,sourceId);return w&&s?{platform:activeAdapter.platform,workspaceId:w.id,workspaceName:w.name,sourceId:s.id,sourceName:s.name,url:s.url,serverId:w.id,serverName:w.name,channelId:s.id,channelName:s.name}:null;}
function renderNavigateChannels(){const wid=serverSelect.value;fill(channelSelect,navigation.sourcesByWorkspace?.[wid]||[],navigation.current?.workspaceId===wid?navigation.current.sourceId:null);updateAvailability();}
function renderBatchChannels(){fill(batchChannels,navigation.sourcesByWorkspace?.[batchServer.value]||[]);updateAvailability();}
function renderProfiles(){profileSelect.innerHTML='';for(const p of profiles){const o=document.createElement('option');o.value=p.id;o.textContent=`${p.name} (${(p.targets||p.sources||[]).length})`;profileSelect.appendChild(o);}profileSelect.disabled=!profiles.length;deleteProfileButton.disabled=!profiles.length;updateAvailability();}
function selectedBatchTargets(){return Array.from(batchChannels.selectedOptions).map(o=>targetFrom(batchServer.value,o.value)).filter(Boolean);}
function selectedProfile(){return profiles.find(p=>p.id===profileSelect.value)||null;}
function updateAvailability(){const mode=sourceMode.value;let ok=Boolean(activeTabId);if(mode==='navigate')ok=ok&&Boolean(channelSelect.value);if(mode==='batch')ok=ok&&selectedBatchTargets().length>0;if(mode==='profile')ok=ok&&Boolean(selectedProfile());exportButton.disabled=!ok;topologyButton.disabled=!activeTabId||!navigation.current?.workspaceId||navigation.current?.isDirect;}
function updateMode(){const mode=sourceMode.value;navigationFields.hidden=mode!=='navigate';batchFields.hidden=mode!=='batch';profileFields.hidden=mode!=='profile';sourceHint.textContent=activeAdapter.hints?.[mode]||'';exportButton.textContent=mode==='batch'||mode==='profile'?(activeAdapter.labels?.executeBatch||'Execute Batch Collection'):(activeAdapter.labels?.collect||'Execute Collection');updateAvailability();}
function applyAdapterUi(adapter){activeAdapter=adapter||activeAdapter;const labels=activeAdapter.labels||{},operations=activeAdapter.operations||[];for(const option of sourceMode.options){option.hidden=operations.length&&!operations.includes(option.value);if(labels[option.value])option.textContent=labels[option.value];}for(const id of ['server','batchServer'])document.querySelector(`label[for="${id}"]`).textContent=labels.workspace||'Workspace';for(const id of ['channel','batchChannels'])document.querySelector(`label[for="${id}"]`).textContent=labels.source||'Source';topologyButton.textContent=labels.topology||'Export Topology';topologyButton.hidden=operations.length&&!operations.includes('topology');}
sourceMode.addEventListener('change',updateMode);serverSelect.addEventListener('change',renderNavigateChannels);channelSelect.addEventListener('change',updateAvailability);batchServer.addEventListener('change',renderBatchChannels);batchChannels.addEventListener('change',updateAvailability);profileSelect.addEventListener('change',updateAvailability);

async function refresh(force=false){const r=await send({action:'getNavigationSnapshot',forceRefresh:force});if(!r.success)throw new Error(r.error);applyAdapterUi(r.adapter);navigation=r.uiNavigation;currentConversation=r.currentConversation;profiles=r.profiles||[];fill(serverSelect,navigation.workspaces,navigation.current?.workspaceId);fill(batchServer,navigation.workspaces,navigation.current?.workspaceId);renderNavigateChannels();renderBatchChannels();renderProfiles();updateMode();}
refreshButton.addEventListener('click',async()=>{setStatus('Refreshing navigation cache...');try{await refresh(true);setStatus('Navigation cache refreshed.');}catch(e){setStatus(`Refresh failed:\n${e.message}`);}});
refreshProfilesButton.addEventListener('click',()=>refresh(false));
saveProfileButton.addEventListener('click',async()=>{try{const targets=selectedBatchTargets();if(!targets.length)throw new Error('Select at least one source.');const options=getOptions();const name=profileName.value.trim()||`Collection mission ${new Date().toLocaleDateString()}`;const r=await send({action:'saveProfile',profile:{name,platform:activeAdapter.platform,strategy:'batch',targets,intent:'archival',runtimePolicy:options.runtimePolicy,options}});if(!r.success)throw new Error(r.error);setStatus(`Mission saved: ${r.profile.name}`);await refresh(false);}catch(e){setStatus(`Mission save failed:\n${e.message}`);}});
deleteProfileButton.addEventListener('click',async()=>{const p=selectedProfile();if(!p)return;const r=await send({action:'deleteProfile',profileId:p.id});if(r.success){profiles=r.profiles;renderProfiles();setStatus(`Deleted profile: ${p.name}`);}else setStatus(`Delete failed:\n${r.error}`);});
healthButton.addEventListener('click',async()=>{const r=await send({action:'getRuntimeReport'});if(!r.success)return setStatus(`Health report failed:\n${r.error}`);const c=r.report.capabilities,a=r.report.adapterContract;setStatus(`Runtime healthy: ${a.valid?'yes':'no'}\nAdapter contract: ${a.valid?'valid':'missing '+a.missing.join(', ')}\nDiscovery: ${c.discovery?'yes':'no'}\nTopology discovery: ${c.topologyDiscovery?'yes':'no'}\nNavigation: ${c.navigation?'yes':'no'}\nBatch: ${r.report.architecturalChecks.batchStrategy?'yes':'no'}\nProfiles: ${r.report.architecturalChecks.profiles?'yes':'no'}\nLog entries: ${r.logs.length}`);});

topologyButton.addEventListener('click',async()=>{topologyButton.disabled=true;setStatus('Observing the current topology...');try{const r=await send({action:'exportServerTopology',format:'json',intent:'archival'});if(!r.success)throw new Error(r.error);const s=r.statistics;setStatus(`Topology export complete.\nCategories: ${s.categories}\nChannels: ${s.channels}\nThreads: ${s.threads}\nForums: ${s.forums}\nCollectible: ${s.collectible}\nKnown unreadable: ${s.knownUnreadable}`);}catch(e){setStatus(`Topology export failed:\n${e.message}`);}finally{updateAvailability();}});

monitorButton.addEventListener('click',()=>chrome.tabs.create({url:chrome.runtime.getURL('status.html')}));

exportButton.addEventListener('click',async()=>{exportButton.disabled=true;try{const mode=sourceMode.value,options=getOptions();if(mode==='current'||mode==='navigate'){const request={action:'executeExport',strategy:mode,options};if(mode==='navigate'){const target=targetFrom(serverSelect.value,channelSelect.value);if(!target)throw new Error('Select a valid target.');request.target=target;setStatus(`Collecting ${target.serverName} / ${target.channelName}...\nYou may close this popup and use Collection Monitor.`);}else setStatus(`Collecting ${activeAdapter.labels?.current||'the current source'}...\nYou may close this popup and use Collection Monitor.`);const r=await send(request);if(!r.success){const partial=r.partialDownloaded?'\nA partial JSON archive was downloaded.':'';throw new Error(`${r.failure?.code?`[${r.failure.code}] `:''}${r.error}${partial}`);}const warnings=(r.warnings||[]).length?`\nWarnings:\n- ${r.warnings.join('\n- ')}`:'';setStatus(`Collection ${r.collectionComplete?'complete':'partial'}.\nMessages: ${r.count}\nParticipants: ${r.participantCount}\nOldest: ${r.earliestCollected||'unknown'}\nNewest: ${r.latestCollected||'unknown'}\nStop reason: ${r.stopReason||'completed'}\nRestored: ${r.restored?'yes':'no'}${warnings}`);}else{const profile=mode==='profile'?selectedProfile():null;const targets=profile?.targets||profile?.sources||selectedBatchTargets();const batchOptions={...(profile?.options||options),format:'json',intent:'archival'};setStatus(`Executing batch across ${targets.length} sources...\n${activeAdapter.name} will navigate sequentially.`);const r=await send({action:'executeBatch',targets,options:batchOptions,profileId:profile?.id||null},240);if(!r.success&&!r.manifest)throw new Error(r.error||'Batch failed.');const t=r.manifest.totals;setStatus(`Batch complete.\nTargets: ${t.targets}\nSuccess: ${t.success}\nWarnings: ${t.warning}\nFailed: ${t.failed}\nMessages: ${t.messages}\nRestored: ${r.manifest.restored?'yes':'no'}\nA batch manifest was downloaded.`);}await refresh(false);}catch(e){setStatus(`Collection failed:\n${e.message}\nOpen Collection Monitor for recovery and diagnostics.`);}finally{updateAvailability();}});

updateTimeControls();

(async()=>{try{const tab=await getActivePlatformTab();activeTabId=tab.id;await refresh(true);const recovery=await send({action:'getCollectionStatus'});const checkpoint=recovery?.checkpoint;const recoveryNotice=checkpoint?.recoverable?`\n\nRecovery available: ${checkpoint.bufferedMessages} messages\nOldest collected: ${checkpoint.earliestLoaded||'unknown'}\nSaved: ${checkpoint.savedAt}\nOpen Collection Monitor to download or resume.`:'';setStatus(`Ready.\nAdapter: ${activeAdapter.name||activeAdapter.platform}\nCurrent: ${currentConversation?.conversation?.name||'source'}\nMissions: ${profiles.length}${recoveryNotice}`);}catch(e){setStatus(`Startup failed:\n${e.message}`);}})();
