const $ = id => document.getElementById(id);
const sourceMode=$('sourceMode'), sourceHint=$('sourceHint'), navigationFields=$('navigationFields'), batchFields=$('batchFields'), profileFields=$('profileFields');
const serverSelect=$('server'), channelSelect=$('channel'), batchServer=$('batchServer'), batchChannels=$('batchChannels');
const profileName=$('profileName'), profileSelect=$('profileSelect'), saveProfileButton=$('saveProfileButton'), deleteProfileButton=$('deleteProfileButton'), refreshProfilesButton=$('refreshProfilesButton');
const range=$('range'), customRange=$('customRange'), startInput=$('start'), endInput=$('end'), format=$('format'), loadOlder=$('loadOlder');
const exportButton=$('exportButton'), refreshButton=$('refreshButton'), healthButton=$('healthButton'), status=$('status');
let activeTabId=null, navigation={servers:[],channelsByServer:{}}, currentConversation=null, profiles=[];
const setStatus=message=>{status.textContent=message;};
range.addEventListener('change',()=>{customRange.hidden=range.value!=='custom';});

function getBounds(){const now=new Date();let start=null,end=null;if(range.value==='24h')start=new Date(now-86400000);if(range.value==='48h')start=new Date(now-172800000);if(range.value==='7d')start=new Date(now-604800000);if(range.value==='custom'){if(!startInput.value||!endInput.value)throw new Error('Choose both a start and end time.');start=new Date(startInput.value);end=new Date(endInput.value);if(!Number.isFinite(start.getTime())||!Number.isFinite(end.getTime())||start>=end)throw new Error('The custom time range is invalid.');}return{startIso:start?start.toISOString():null,endIso:end?end.toISOString():null};}
function getOptions(){return{...getBounds(),format:format.value,loadOlder:loadOlder.checked};}
async function getActiveDiscordTab(){const[tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab?.id||!tab.url?.startsWith('https://discord.com/'))throw new Error('Open Discord in the active Chrome tab first.');return tab;}
async function send(message,attempts=80){let lastError;for(let i=0;i<attempts;i++){try{const response=await chrome.tabs.sendMessage(activeTabId,message);if(response)return response;}catch(error){lastError=error;}await new Promise(r=>setTimeout(r,300));}throw new Error(lastError?.message||'Could not connect to Discord.');}
function fill(select,items,selected=null){select.innerHTML='';for(const item of items){const o=document.createElement('option');o.value=item.id;o.textContent=item.name;o.dataset.url=item.url||'';if(item.id===selected)o.selected=true;select.appendChild(o);}select.disabled=!items.length;}
function serverById(id){return navigation.servers.find(x=>x.id===id)||null;}
function channelById(serverId,id){return(navigation.channelsByServer?.[serverId]||[]).find(x=>x.id===id)||null;}
function targetFrom(serverId,channelId){const s=serverById(serverId),c=channelById(serverId,channelId);return s&&c?{platform:'discord',serverId:s.id,serverName:s.name,channelId:c.id,channelName:c.name,url:c.url}:null;}
function renderNavigateChannels(){const sid=serverSelect.value;fill(channelSelect,navigation.channelsByServer?.[sid]||[],navigation.current?.serverId===sid?navigation.current.channelId:null);updateAvailability();}
function renderBatchChannels(){fill(batchChannels,navigation.channelsByServer?.[batchServer.value]||[]);updateAvailability();}
function renderProfiles(){profileSelect.innerHTML='';for(const p of profiles){const o=document.createElement('option');o.value=p.id;o.textContent=`${p.name} (${p.targets.length})`;profileSelect.appendChild(o);}profileSelect.disabled=!profiles.length;deleteProfileButton.disabled=!profiles.length;updateAvailability();}
function selectedBatchTargets(){return Array.from(batchChannels.selectedOptions).map(o=>targetFrom(batchServer.value,o.value)).filter(Boolean);}
function selectedProfile(){return profiles.find(p=>p.id===profileSelect.value)||null;}
function updateAvailability(){const mode=sourceMode.value;let ok=Boolean(activeTabId);if(mode==='navigate')ok=ok&&Boolean(channelSelect.value);if(mode==='batch')ok=ok&&selectedBatchTargets().length>0;if(mode==='profile')ok=ok&&Boolean(selectedProfile());exportButton.disabled=!ok;}
function updateMode(){const mode=sourceMode.value;navigationFields.hidden=mode!=='navigate';batchFields.hidden=mode!=='batch';profileFields.hidden=mode!=='profile';sourceHint.textContent={current:'Collects whatever is currently displayed, including DMs, group DMs, threads, forums, and channels.',navigate:'Collects one passively cached server channel and restores the original view.',batch:'Collects multiple cached channels sequentially and downloads a batch manifest.',profile:'Runs a previously saved collection plan.'}[mode];exportButton.textContent=mode==='batch'||mode==='profile'?'Execute Batch Collection':'Execute Collection';updateAvailability();}
sourceMode.addEventListener('change',updateMode);serverSelect.addEventListener('change',renderNavigateChannels);channelSelect.addEventListener('change',updateAvailability);batchServer.addEventListener('change',renderBatchChannels);batchChannels.addEventListener('change',updateAvailability);profileSelect.addEventListener('change',updateAvailability);

async function refresh(force=false){const r=await send({action:'getNavigationSnapshot',forceRefresh:force});if(!r.success)throw new Error(r.error);navigation=r.navigation;currentConversation=r.currentConversation;profiles=r.profiles||[];fill(serverSelect,navigation.servers,navigation.current?.serverId);fill(batchServer,navigation.servers,navigation.current?.serverId);renderNavigateChannels();renderBatchChannels();renderProfiles();updateMode();}
refreshButton.addEventListener('click',async()=>{setStatus('Refreshing navigation cache...');try{await refresh(true);setStatus('Navigation cache refreshed.');}catch(e){setStatus(`Refresh failed:\n${e.message}`);}});
refreshProfilesButton.addEventListener('click',()=>refresh(false));
saveProfileButton.addEventListener('click',async()=>{try{const targets=selectedBatchTargets();if(!targets.length)throw new Error('Select at least one channel.');const name=profileName.value.trim()||`Batch profile ${new Date().toLocaleDateString()}`;const r=await send({action:'saveProfile',profile:{name,strategy:'batch',targets,options:getOptions()}});if(!r.success)throw new Error(r.error);setStatus(`Profile saved: ${r.profile.name}`);await refresh(false);}catch(e){setStatus(`Profile save failed:\n${e.message}`);}});
deleteProfileButton.addEventListener('click',async()=>{const p=selectedProfile();if(!p)return;const r=await send({action:'deleteProfile',profileId:p.id});if(r.success){profiles=r.profiles;renderProfiles();setStatus(`Deleted profile: ${p.name}`);}else setStatus(`Delete failed:\n${r.error}`);});
healthButton.addEventListener('click',async()=>{const r=await send({action:'getRuntimeReport'});if(!r.success)return setStatus(`Health report failed:\n${r.error}`);const c=r.report.capabilities,a=r.report.adapterContract;setStatus(`Runtime healthy: ${a.valid?'yes':'no'}\nAdapter contract: ${a.valid?'valid':'missing '+a.missing.join(', ')}\nDiscovery: ${c.discovery?'yes':'no'}\nNavigation: ${c.navigation?'yes':'no'}\nBatch: ${r.report.architecturalChecks.batchStrategy?'yes':'no'}\nProfiles: ${r.report.architecturalChecks.profiles?'yes':'no'}\nLog entries: ${r.logs.length}`);});

exportButton.addEventListener('click',async()=>{exportButton.disabled=true;try{const mode=sourceMode.value,options=getOptions();if(mode==='current'||mode==='navigate'){const request={action:'executeExport',strategy:mode,options};if(mode==='navigate'){const target=targetFrom(serverSelect.value,channelSelect.value);if(!target)throw new Error('Select a valid target.');request.target=target;setStatus(`Collecting ${target.serverName} / ${target.channelName}...`);}else setStatus('Collecting the current conversation...');const r=await send(request);if(!r.success)throw new Error(r.error);setStatus(`Collection complete.\nMessages: ${r.count}\nParticipants: ${r.participantCount}\nComplete: ${r.collectionComplete?'yes':'no'}\nRestored: ${r.restored?'yes':'no'}`);}else{const profile=mode==='profile'?selectedProfile():null;const targets=profile?.targets||selectedBatchTargets();const batchOptions=profile?.options||options;setStatus(`Executing batch across ${targets.length} targets...\nDiscord will navigate sequentially.`);const r=await send({action:'executeBatch',targets,options:batchOptions,profileId:profile?.id||null},240);if(!r.success&&!r.manifest)throw new Error(r.error||'Batch failed.');const t=r.manifest.totals;setStatus(`Batch complete.\nTargets: ${t.targets}\nSuccess: ${t.success}\nWarnings: ${t.warning}\nFailed: ${t.failed}\nMessages: ${t.messages}\nRestored: ${r.manifest.restored?'yes':'no'}\nA batch manifest was downloaded.`);}await refresh(false);}catch(e){setStatus(`Collection failed:\n${e.message}`);}finally{updateAvailability();}});

(async()=>{try{const tab=await getActiveDiscordTab();activeTabId=tab.id;await refresh(true);setStatus(`Ready.\nCurrent: ${currentConversation?.conversation?.name||'conversation'}\nProfiles: ${profiles.length}`);}catch(e){setStatus(`Startup failed:\n${e.message}`);}})();
